### ISSUE TITLE
Cannot click on sidebar

### ISSUE THREAD

**Issue by iamkhattar** [chocoford/ExcalidrawZ#53]
Hey thanks for maintaining this app, this has been a great productivity boost!

I've recently upgraded to Version 1.2.4 (26) and I have noticed that I cannot click on any of the drawings I have on the sidebar. I can still click and change folders just not the individual drawings available in the folders.

This behaviour is consistent across two devices. One device is a MacBook Air running MacOS 15.0.1 and another device is a MacBook Pro running MacOS 14.

https://github.com/user-attachments/assets/beedec5c-e581-4952-8839-a3522764d372

**Comment by chocoford** [comment]
Hello, I sincerely apologize for this issue. It seems to be an isolated bug, and I’ll need some time to identify the cause.

**Comment by chocoford** [comment]
Can you right-click to bring up the menu for the second “Untitled” file?

**Comment by iamkhattar** [comment]
Hey, thanks for getting back to this and sorry for the delay in replying to this.

Here is what the right click shows me:

<img width="346" alt="image" src="https://github.com/user-attachments/assets/0d4c1be7-5211-42ae-8e65-b39fb0164194">

<img width="346" alt="image" src="https://github.com/user-attachments/assets/38443c73-cf1e-4c88-bbf5-be4483f38115">

**Comment by chocoford** [comment]
This is a very strange issue. You can try the following:
- Try clicking on the text portion of the button (Untitled) instead of the blank area.
- Attempt to duplicate the unloaded file and check if it switches to the newly duplicated file.
- Delete these two files and recreate them to see if the issue persists.

Also, may I ask if both devices are logged into the same iCloud account? If they are, it might indicate a data synchronization issue between the devices. If not, you can disregard this part.

**Comment by egbertp** [comment]
Hi @chocoford : Great app,  thank you very much for your time and effort! 

I have exactly the same issue as @iamkhattar : Switching to different groups via the left sidebar works. However, when I try to click on a different file, nothing happens. 

https://github.com/user-attachments/assets/3779c53a-fc46-4811-a254-e2c8bd6d6c1a

Can I help you debug the issue? I've joined your Discord server, if needed you can approach me via that way. 

Thanks in advance for your time!

**Comment by iamkhattar** [comment]
Hey sorry for the delayed reply here and thanks again for looking into this.

Here is a screengrab of the stuff you asked for:

1. It does not seem to let me change the diagram no matter where I click :(
2. Duplication of the file does work, this is the trick I am using in the interim to access old diagrams
3. Deleting and recreating the files still persists this issue

https://github.com/user-attachments/assets/711ebe4b-be9f-4387-9c35-5a054fc80beb

Both the devices are isolated and are not on the same iCloud account if it helps.

Thank you for the suggestion @egbertp. Unfortunately when I unintstall my current version and install straight from the `1.1.0` dmg I get the following error:
[logs.txt](https://github.com/user-attachments/files/18030297/logs.txt)

**Comment by chocoford** [comment]
Yes, enabling iCloud synchronization in the new version does cause compatibility issues, making it impossible to downgrade to older versions.

Since the new version (v1.2.0+) has changed the data structure, **if you have important data files, downgrading is not recommended**.

If you still wish to downgrade, the app needs to be reset. Here are the steps:

**1. Backup your files (if any)**

Copy the backup files created by ExcalidrawZ to your Downloads folder:
```bash
cp -r ~/Library/Containers/com.chocoford.excalidraw/Data/Library/Application\ Support/backups ~/Downloads/ExcalidrawZ_backups
```
Make sure the backup has been successfully copied.

**2. Reset the app**

Run the following command to reset the app:
``` bash
rm -rf ~/Library/Containers/com.chocoford.excalidraw
```
After resetting, you can install the older version and start fresh. Let me know if you have any questions!

**Comment by iamkhattar** [comment]
Thank you so much, I have managed to get one of my laptops working with v1.1.0. Unfortunately I do not have the perms on the other one to be able to install older versions, so I will wait for whenever this is fixed. Thank you so much for your help and this project is great keep up the good stuff :D

**Comment by chocoford** [comment]
Hello, @iamkhattar.
[Here](https://drive.google.com/file/d/1sIExaEctCQas0KBcTpYieBSHJ96StqGW/view?usp=share_link) is a build without the file renaming feature. Could you help me check if the sidebar is functioning properly?

**Comment by iamkhattar** [comment]
Hey @chocoford thanks for the quick turnaround on this. I can confirm the sidebar indeed does work as intended in the update you sent, however, the folders seem to be duplicated. i.e. there is two default and two recently deleted folders. Thanks again for the great app!

**Comment by chocoford** [comment]
Hello, @iamkhattar. Thank you so much for your help with testing—it’s been a tremendous help.

Regarding the duplicated `default` and `recently deleted` folders you mentioned, this is likely caused by iCloud synchronizing data files from other devices. Normally, these duplicated folders should be merged once the data synchronization is complete. However, a logic flaw may have prevented this step from executing successfully.

Nevertheless, ExcalidrawZ is also designed to perform this merging operation each time it runs. Could you check again after reopening the app to see if these duplicated folders are still there? Let me know the results! 😊

**Comment by chocoford** [comment]
Hello, @iamkhattar. The new version of `ExcalidrawZ`(v1.2.6) has been released. Unfortunately, after running this version, the sidebar is still not functioning properly for @egbertp . If you have the time, could you help me double-check whether the sidebar is working correctly on your device? Your assistance would be greatly appreciated! 😊

**Comment by iamkhattar** [comment]
Hey @chocoford, thanks for looking, so, I reopened the application and the duplicate folders did go away, nice catch there!

As for trying the update, I have now tried the update on two devices and the sidebar issue is present on one of the device whereas it's been fixed on the other device.

Do let me know if you need me to test something else and thanks for looking into this :D

**Comment by chocoford** [comment]
Hello @iamkhattar, sorry for disturbing. I need your help testing this build to see if the sidebar clicking issue still persists. 
Here is the download link: https://drive.google.com/file/d/1KgbxpidUQDsSDTyvMr1PnYhD9Knbol7g/view?usp=share_link

**Comment by iamkhattar** [comment]
Hey @chocoford really sorry the late reply I completely missed this notification. I would’ve tested this but unfortunately the laptop where the sidebar issue persists doesn’t let me install dmgs that have not originated from brew. It’s to do with permissions that I have on the laptop which unfortunately I can’t change. I will be trying this update out on a couple of devices my friends own tomorrow, and will report back here. Again really sorry for the delay and thanks for looking into this

**Comment by chocoford** [comment]
@iamkhattar It’s okay; this build has already been confirmed by other users to not have resolved the issue.

**Comment by bzadon** [comment]
i am having this problem too. i am a new user and this happened right after installing for the first time. please help!

**Comment by chocoford** [comment]
Hello, @bzadon. I am fixing this issue. I apologize for the unpleasant experience. The new version is expected to be released within 2-3 days and includes a fix for this issue. At that time, I will need your help to verify whether the problem has been resolved. Thank you for your patience!

**Comment by bzadon** [comment]
TY for fixing. It works!
